---
title: "ESAm 211 Final Project"
author: "Becky Clow and Priscilla Hare"
date: "2/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(popbio)
library(primer)
library(tidyverse)
```

Starting stages:
seedbank:5000
rosette:500
adult:100

Alliaria petiolate Matrix
```{r}

gb =  0.3171
s = 0.025
f = 616
v = 0.8228
gi =  0.5503

life_stages <- c("Seedbank", "Rosette", "Adult")
original_matrix <- matrix(c(1-gb, 0, f*v*(1-gi),
                          gb,   0, f*v*gi,
                          0,    s, 0),
                          nrow = 3, ncol = 3, byrow = TRUE, dimnames = list(life_stages,life_stages))

print(original_matrix)

```

Part 2: Projecting the Matrix
```{r}

n_0 <- c(5000, 500, 100) #initial abundance
pop_1 <- pop.projection(original_matrix, n_0, iterations = 50) #initial population
stage.vector.plot(pop_1$stage.vector) #proportions
stage.vector.plot(pop_1$stage.vector, proportions = FALSE)

```

```{r}
plot(pop_1$pop.sizes)
plot(pop_1$pop.changes)

```



```{r}
lambda(original_matrix)
stable.stage(original_matrix)
DemoInfo(original_matrix)
```


Manual sensitivity analysis

```{r}
#Manipulating seedling survival s
original_matrix[3,2] <- 0.02
lambda(original_matrix)

original_matrix[3,2] <- 0.01
lambda(original_matrix)

original_matrix[3,2] <- 0.008
lambda(original_matrix)

original_matrix[3,2] <- 0.004
lambda(original_matrix)

original_matrix[3,2] <- 0.002
lambda(original_matrix)

original_matrix[3,2] <- 0.0019
lambda(original_matrix)

```

```{r}
original_matrix[3,2] <- 0.025

#manual manipulation f
gb =  0.3171
s = 0.025
f = 49
v = 0.8228
gi =  0.5503

life_stages <- c("Seedbank", "Rosette", "Adult")
original_matrix_f <- matrix(c(1-gb, 0, f*v*(1-gi),
                          gb,   0, f*v*gi,
                          0,    s, 0),
                          nrow = 3, ncol = 3, byrow = TRUE, dimnames = list(life_stages,life_stages))

lambda(original_matrix_f)

#f would have to be below 49 to get below a 1 lambda

```


Part 4: Sensitivity
```{r}
original_matrix <- matrix(c(1-gb, 0, f*v*(1-gi),
                          gb,   0, f*v*gi,
                          0,    s, 0),
                          nrow = 3, ncol = 3, byrow = TRUE, dimnames = list(life_stages,life_stages))

original_matrix


DemoInfo(original_matrix)
```
highest elasticity: rosette to adult, adult to rosette (not biologically possible)

Part 5: elasticity to vital rates
```{r}
A.vr <- expression(1-gb, 0, f*v*(1-gi),
                          gb,   0, f*v*gi,
                          0,    s, 0)

vr.vals <- list(gb = 0.3171, f = 616, v = 0.8228, gi = 0.5503, s = 0.025)

vitalsens(A.vr, vr.vals)
```

f, v, and s are the most elastic